my_string= input ('Введите строку ')
len_type = str(len)
string_long = len(my_string)
max_type = str(max)
string_max = max(my_string)
min_type = str(min)
string_min = min(my_string)
print('Длина строки', string_long, 'символов, функция len', len_type)
print('Максимальный символ:', string_max, ', функция max', max_type)
print('Минимальный символ:', string_min, ', функция min', min_type)